import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navigation from "./components/Navigation";
import Providers from "./components/Providers";

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-dvh bg-neutral-50 dark:bg-neutral-900">
      <body
        className={`${roboto.variable} antialiased flex flex-col h-dvh`}
      >
        <Providers>
          <Navigation />
          <main className="flex-1 min-h-0">
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
